//
//package tn.esprit.esook.client.swing;
//
//import javax.naming.Context;
//import javax.naming.InitialContext;
//import javax.swing.GroupLayout;
//import javax.swing.GroupLayout.Alignment;
//import javax.swing.LayoutStyle.ComponentPlacement;
//
//import tn.edu.esprit.Pidev.Entity.Admin;
//
///**
// * 
// * @author Badreddine
// */
//public class UpdateAdmin extends javax.swing.JFrame {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 1L;
//
//	/**
//	 * Creates new form NewJFrame
//	 */
//	public UpdateAdmin() {
//		initComponents();
//	}
//
//	/**
//	 * This method is called from within the constructor to initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is always
//	 * regenerated by the Form Editor.
//	 */
//
//	private void initComponents() {
//
//		jPanel1 = new javax.swing.JPanel();
//		jLabel1 = new javax.swing.JLabel();
//		jLabel2 = new javax.swing.JLabel();
//		jLabel3 = new javax.swing.JLabel();
//		jLabel4 = new javax.swing.JLabel();
//		jTextField1 = new javax.swing.JTextField();
//		jTextField2 = new javax.swing.JTextField();
//		jTextField3 = new javax.swing.JTextField();
//		jButton1 = new javax.swing.JButton();
//		jLabel5 = new javax.swing.JLabel();
//		jPasswordField1 = new javax.swing.JPasswordField();
//		jLabel6 = new javax.swing.JLabel();
//		jTextField4 = new javax.swing.JTextField();
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//		jLabel1.setText("");
//
//		jLabel2.setText("Last name:");
//
//		jLabel3.setText("Login:");
//
//		jLabel4.setText("Password:");
//
//		jTextField1.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextField1ActionPerformed(evt);
//			}
//		});
//
//		jTextField2.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextField2ActionPerformed(evt);
//			}
//		});
//
//		jTextField3.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextField3ActionPerformed(evt);
//			}
//		});
//
//		jButton1.setText("OK");
//		jButton1.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton1ActionPerformed(evt);
//			}
//		});
//
//		jLabel5.setText("Admin Registration");
//
//		jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jPasswordField1ActionPerformed(evt);
//			}
//		});
//
//		jLabel6.setText("CIN");
//
//		jTextField4.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jTextField4ActionPerformed(evt);
//			}
//		});
//
//		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
//				jPanel1);
//		jPanel1Layout.setHorizontalGroup(
//			jPanel1Layout.createParallelGroup(Alignment.LEADING)
//				.addGroup(jPanel1Layout.createSequentialGroup()
//					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
//						.addGroup(jPanel1Layout.createSequentialGroup()
//							.addGap(28)
//							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
//								.addComponent(jButton1)
//								.addGroup(jPanel1Layout.createSequentialGroup()
//									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
//										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
//											.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
//											.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//											.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
//											.addComponent(jLabel6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//											.addComponent(jLabel4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//									.addGap(87)
//									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
//										.addComponent(jTextField1, 293, 293, 293)
//										.addComponent(jTextField2, 293, 293, 293)
//										.addComponent(jTextField3, 293, 293, 293)
//										.addComponent(jPasswordField1, 293, 293, 293)
//										.addComponent(jTextField4, 293, 293, 293)))))
//						.addGroup(jPanel1Layout.createSequentialGroup()
//							.addGap(235)
//							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 211, GroupLayout.PREFERRED_SIZE)))
//					.addGap(240))
//		);
//		jPanel1Layout.setVerticalGroup(
//			jPanel1Layout.createParallelGroup(Alignment.LEADING)
//				.addGroup(jPanel1Layout.createSequentialGroup()
//					.addGap(25)
//					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
//						.addGroup(jPanel1Layout.createSequentialGroup()
//							.addComponent(jLabel5)
//							.addGap(64)
//							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
//								.addComponent(jLabel1)
//								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//							.addGap(44)
//							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
//								.addComponent(jLabel2)
//								.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//							.addGap(48)
//							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
//								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
//								.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//							.addGap(44)
//							.addComponent(jLabel4))
//						.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
//					.addGap(52)
//					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
//						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
//						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
//					.addPreferredGap(ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
//					.addComponent(jButton1)
//					.addContainerGap())
//		);
//		jPanel1.setLayout(jPanel1Layout);
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
//				getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout.createParallelGroup(
//				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
//				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
//				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//		layout.setVerticalGroup(layout.createParallelGroup(
//				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
//				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
//				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
//
//		pack();
//	}// </editor-fold>
//
//	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//	}
//
//	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//		try {
//			Context context = new InitialContext();
//			GestionAdminRemote gestionAdminRemote = (GestionAdminRemote) context
//					.lookup("ejb:/Pidev/GestionAdmin!tn.edu.esprit.Pidev.services.GestionAdminRemote");
//			Admin admin = new Admin();
//			admin.setFirstName(jTextField1.getText());
//			admin.setLastName(jTextField2.getText());
//			admin.setLogin(jTextField3.getText());
//			admin.setPassword(jPasswordField1.getText());
//			admin.setCin(Integer.valueOf(jTextField4.getText()));
//			
//			
//			gestionAdminRemote.persistAdmin(admin);
//
//		} catch (Exception e) {
//			e.printStackTrace();
//		}
//	}
//
//	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//	}
//
//	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//	}
//
//	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//	}
//
//	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
//		// TODO add your handling code here:
//	}
//
//	/**
//	 * @param args
//	 *            the command line arguments
//	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		// <editor-fold defaultstate="collapsed"
//		// desc=" Look and feel setting code (optional) ">
//		/*
//		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
//		 * default look and feel. For details see
//		 * http://download.oracle.com/javase
//		 * /tutorial/uiswing/lookandfeel/plaf.html
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
//					.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(
//					java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(
//					java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(
//					java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(
//					java.util.logging.Level.SEVERE, null, ex);
//		}
//		// </editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new UpdateAdmin().setVisible(true);
//			}
//		});
//	}
//
//	// Variables declaration - do not modify
//	private javax.swing.JButton jButton1;
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JLabel jLabel2;
//	private javax.swing.JLabel jLabel3;
//	private javax.swing.JLabel jLabel4;
//	private javax.swing.JLabel jLabel5;
//	private javax.swing.JLabel jLabel6;
//	private javax.swing.JPanel jPanel1;
//	private javax.swing.JPasswordField jPasswordField1;
//	private javax.swing.JTextField jTextField1;
//	private javax.swing.JTextField jTextField2;
//	private javax.swing.JTextField jTextField3;
//	private javax.swing.JTextField jTextField4;
//	// End of variables declaration
//}
